apiVersion: v1
kind: ConfigMap
metadata:
  name: upi-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "upi.labels" . | nindent 4 }}
data:
  KAFKA_BROKERS: {{ .Values.global.kafka.brokers | quote }}
  REDIS_ADDR: {{ .Values.global.redis.addr | quote }}
  INGESTION_URL: http://tx-ingestion:8081
  ANALYTICS_URL: http://analytics:8089
  MAX_RETRY_ATTEMPTS: "5"
