apiVersion: v1
kind: Secret
metadata:
  name: upi-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "upi.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-dsn: {{ include "upi.postgresDsn" . | quote }}
  api-keys: {{ .Values.global.apiKeys | quote }}
