apiVersion: v2
name: upi-platform
description: UPI Transaction Intelligence & Failure Recovery Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - upi
  - kafka
  - fintech
  - observability
maintainers:
  - name: UPI Platform Team
